[project]
name = "sweeper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-loop>=1.0.13",
    "ruff>=0.11.2",
]
